<a href="https://colab.research.google.com/github/fc63/gender-classification/blob/main/combine_informal/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
import pandas as pd
import pickle
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

input_path = "/content/drive/MyDrive/datasets/blogs_gender_df.pkl"

with open(input_path, "rb") as f:
    df = pickle.load(f)

In [52]:
df

,text,gender
0,It's getting COLD!!!! what the hell is going on?? *Shakes head in disgrace* but its a funny thing...my house feels like I have...get this...AIR CONDITIONING....geee. Well...I am deciding if I would still want to go see the West Side Story outside on a big screen...it's supposed to start by sundown but it looks like it's gonna rain...so maybe not. I had the wierdest dream....I WAS XENA!! lol and i was eating....cheese!! Cheese apparently made me invincible..it was scary. But who doesnt love cheese....^_^ now that u've read this...go on...I urge you...have some cheese *WINK*,male
1,"Hey I know its a little late, but I just found this image, it cracked me up! By the way it's from urlLink Beer Monkey The image that was perviously here awas messing up the site design so I removed it. If you want to see it urlLink click here .",male
2,"fourthling (11:06:39 PM): You've gone monosyllabic Tevren7891 (11:06:44 PM): ?? fourthling (11:06:51 PM): Quiet fourthling (11:06:57 PM): One word response sorta stuff Tevren7891 (11:07:00 PM): but but but fourthling (11:07:05 PM): Lol!!! fourthling (11:07:06 PM): Very cute Tevren7891 (11:07:07 PM): heh i said but Tevren7891 (11:07:17 PM): heh heh but fourthling (11:07:32 PM): Lol - mommy! he said ""but""!!! Heh. A little peek into my daily life. In case you were wondering I am Tevren7891, and I said ""but""+t. Ha, I crack myself up but not. Anyway meeting up some people and watching movies, probably Braveheart, Shari's favorite. Today was fine expect that I saw a damn Hummer again. It caused me to be blind for three seconds. Also the world is now collapsing if you haven't noticed. Was walking Jaun's dog with him when I noticed that a homeless man had nice leather cushions. Man, a homeless guy with leather cushions! Tired to get the dog to piss on the cushions but it wouldn't. Then tried to make it piss on a really nice car, but again it wouldn't. Life Sucks real bad since that dog didn't piss on the hot car (not Hummer, yet I can dream).",male
3,"Well, I'm an idiot! But a reasonably happy one, nonetheless. I figured out why the AP people never sent me my scores . . . I filled out the address thing wrong. Can you believe that?! How *much* intelligence does it take to bubble something in properly??? I don't even want to know what I got anymore - if I can't write my own name and address, I certainly can't pass the stupid test. Unfortunately, now that I've decided I really *am* just that stupid, they've gotten my actual address and are going to remail my scores. *buries head in hands* In other news . . . um, I figured out how to delete posts all on my own. It's kind of fun - so if anyone's been seeing posts that suddenly disappear five minutes later, that's just me reveling in my one discovered technological skill. It's about the only thing I *can* do. And Conrad. . . you're definitely my favorite little brother ever. Love you lots - maybe we should make a calendar and start marking down days? ^_~ Later!",male
4,"Well...I thought I would make one post before I went to bed so here it is. POST. Anyway saw some friends and had some fun, besides that today was very uneventful. Think tomorrow will be the same, G'night all hope Satan doesn't wake you",male
...,...,...
676621,mood: omg listening to: ... me and sharons hosting the jap students.. its gonna be so fun.. haha. portugal rox!,female
676622,"mood:tired listening to: the air con buzzing sigh. Exams are in like 2 days?! And I'm still online!? This is so shitified. Anyway, please lah. It's just football. Ok. maybe not JUST football but yar, you all roughly get what I mean right? So cool down people. God loves you all and so does Liz who has a massive stomachache now... So seeya guys/gurls.",female
676623,"mood: stressed!! listening to: someday by nickelback hey! sorry just dropped by to tell everyone that part two will be up AFTER THE EXAMS! hehe. oh yeah and pls stop the tagboard war can. the euro doesn't affect us in any way, we don't stand to lose or gain from it do we?",female
676624,"mood: tired listening to: heal the world-michael jackson[yesyes. jacko wacko] where's everyone!?! a good answer would be buried under a big pile of assesment books...heh. Have to admit. I'm turning into a Melody too! ;) Anyhoos Sze, i heard Winnie So's going on the Hong Kong trip as well... Like erm ok... So who's hosting Jap students? Oh and Mich, where's part two of the story?!!! Haha/",female
676625,"mood: - listening to: the windchime tinkling hey ppl. my b'dae is coming soon and all of the RTOL ppl are invited to my b'dae party. its on a saturday, the 28th august. so try to make tt day free if u wanna come. =).. btw, whys this bloggie so ddd",female

In [53]:
import re
import pandas as pd

def remove_chat_logs(df, text_column):
    """
    Blog veri setinden chat log tarzı içerikleri temizler.
    text_column: Temizlenecek yazının bulunduğu sütunun adı
    """
    def is_chat_log(text):
        # 2 veya daha fazla "Saat (AM/PM)" desenini içeriyorsa sohbet olabilir
        time_pattern = r'\d{1,2}:\d{2}\s?(?:AM|PM)'
        matches = re.findall(time_pattern, text, flags=re.IGNORECASE)
        return len(matches) >= 2

    df_cleaned = df[~df[text_column].apply(is_chat_log)].copy()
    return df_cleaned

df = remove_chat_logs(df, text_column="text")

df

,text,gender
0,It's getting COLD!!!! what the hell is going on?? *Shakes head in disgrace* but its a funny thing...my house feels like I have...get this...AIR CONDITIONING....geee. Well...I am deciding if I would still want to go see the West Side Story outside on a big screen...it's supposed to start by sundown but it looks like it's gonna rain...so maybe not. I had the wierdest dream....I WAS XENA!! lol and i was eating....cheese!! Cheese apparently made me invincible..it was scary. But who doesnt love cheese....^_^ now that u've read this...go on...I urge you...have some cheese *WINK*,male
1,"Hey I know its a little late, but I just found this image, it cracked me up! By the way it's from urlLink Beer Monkey The image that was perviously here awas messing up the site design so I removed it. If you want to see it urlLink click here .",male
3,"Well, I'm an idiot! But a reasonably happy one, nonetheless. I figured out why the AP people never sent me my scores . . . I filled out the address thing wrong. Can you believe that?! How *much* intelligence does it take to bubble something in properly??? I don't even want to know what I got anymore - if I can't write my own name and address, I certainly can't pass the stupid test. Unfortunately, now that I've decided I really *am* just that stupid, they've gotten my actual address and are going to remail my scores. *buries head in hands* In other news . . . um, I figured out how to delete posts all on my own. It's kind of fun - so if anyone's been seeing posts that suddenly disappear five minutes later, that's just me reveling in my one discovered technological skill. It's about the only thing I *can* do. And Conrad. . . you're definitely my favorite little brother ever. Love you lots - maybe we should make a calendar and start marking down days? ^_~ Later!",male
4,"Well...I thought I would make one post before I went to bed so here it is. POST. Anyway saw some friends and had some fun, besides that today was very uneventful. Think tomorrow will be the same, G'night all hope Satan doesn't wake you",male
5,"Conrad's taught me how to post - I thought I knew, but apparently it takes more effort. Wow, that's ironic. Dollface, dearest love of my life, I'm going to try to call you later, but be prepared to pick up for a phone number you don't know. LadyNeptune - well, first get a shorter name ^_^ - and I'll try to call you, too. How could I not try to get ahold of my favorite lesbian lover? And Conrad - you're definitely the best friend a demented gypsy could ask for. Even if you won't admit you're my little brother. Sedgie - were you wearing the necklace this morning? I didn't notice - and we're so calling you Sedgie from now on. ^_^ To all the rest of you out there in the ether, it's one of those days. It's one of those lifes. And I've had the same song stuck in my head for weeks and now I can't remember a word. It's something like ""I'm With You"" by some girl. Got it stuck in my head in the bus station in Texas, and now I've lost it. Lost a lot of things. And I can't find the shirt - which oddly enough, is the thing that currently matters most. I'll be seeing you.",male
...,...,...
676621,mood: omg listening to: ... me and sharons hosting the jap students.. its gonna be so fun.. haha. portugal rox!,female
676622,"mood:tired listening to: the air con buzzing sigh. Exams are in like 2 days?! And I'm still online!? This is so shitified. Anyway, please lah. It's just football. Ok. maybe not JUST football but yar, you all roughly get what I mean right? So cool down people. God loves you all and so does Liz who has a massive stomachache now... So seeya guys/gurls.",female
676623,"mood: stressed!! listening to: someday by nickelback hey! sorry just dropped by to tell everyone that part two will be up AFTER THE EXAMS! hehe. oh yeah and pls stop the tagboard war can. the euro doesn't affect us in any way, we don't stand to lose or gain from it do we?",female
676624,"mood: tired listening to: heal the world-michael jackson[yesyes. jacko wacko] where's everyone!?! a good answer would be buried under a big pile of assesment books...heh. Have to admit. I'm turning into a Melody too! ;) Anyhoos Sze, i heard Winnie So's going on the Hong Kong trip as well... Like erm ok... So who's hosting Jap students? Oh and Mich, where's part two of the story?!!! Haha/",female
676625,"mood: - listening to: the windchime tinkling hey ppl. my b'dae is coming soon and all of the RTOL ppl are invited to my b'dae party. its on a saturday, the 28th august. so try to make tt day free if u wanna come. =).. btw, whys this bloggie so ddd",female

In [54]:
def remove_media_caption_rows(df, text_column):
    """
    urlLink gibi medya placeholder'ı içeren, genelde bilgi taşımayan satırları kaldırır.
    """
    pattern = r'^urlLink\s.*\surlLink$'
    df_cleaned = df[~df[text_column].str.match(pattern, case=False, na=False)].copy()
    return df_cleaned

df = remove_media_caption_rows(df, text_column="text")

df

,text,gender
0,It's getting COLD!!!! what the hell is going on?? *Shakes head in disgrace* but its a funny thing...my house feels like I have...get this...AIR CONDITIONING....geee. Well...I am deciding if I would still want to go see the West Side Story outside on a big screen...it's supposed to start by sundown but it looks like it's gonna rain...so maybe not. I had the wierdest dream....I WAS XENA!! lol and i was eating....cheese!! Cheese apparently made me invincible..it was scary. But who doesnt love cheese....^_^ now that u've read this...go on...I urge you...have some cheese *WINK*,male
1,"Hey I know its a little late, but I just found this image, it cracked me up! By the way it's from urlLink Beer Monkey The image that was perviously here awas messing up the site design so I removed it. If you want to see it urlLink click here .",male
3,"Well, I'm an idiot! But a reasonably happy one, nonetheless. I figured out why the AP people never sent me my scores . . . I filled out the address thing wrong. Can you believe that?! How *much* intelligence does it take to bubble something in properly??? I don't even want to know what I got anymore - if I can't write my own name and address, I certainly can't pass the stupid test. Unfortunately, now that I've decided I really *am* just that stupid, they've gotten my actual address and are going to remail my scores. *buries head in hands* In other news . . . um, I figured out how to delete posts all on my own. It's kind of fun - so if anyone's been seeing posts that suddenly disappear five minutes later, that's just me reveling in my one discovered technological skill. It's about the only thing I *can* do. And Conrad. . . you're definitely my favorite little brother ever. Love you lots - maybe we should make a calendar and start marking down days? ^_~ Later!",male
4,"Well...I thought I would make one post before I went to bed so here it is. POST. Anyway saw some friends and had some fun, besides that today was very uneventful. Think tomorrow will be the same, G'night all hope Satan doesn't wake you",male
5,"Conrad's taught me how to post - I thought I knew, but apparently it takes more effort. Wow, that's ironic. Dollface, dearest love of my life, I'm going to try to call you later, but be prepared to pick up for a phone number you don't know. LadyNeptune - well, first get a shorter name ^_^ - and I'll try to call you, too. How could I not try to get ahold of my favorite lesbian lover? And Conrad - you're definitely the best friend a demented gypsy could ask for. Even if you won't admit you're my little brother. Sedgie - were you wearing the necklace this morning? I didn't notice - and we're so calling you Sedgie from now on. ^_^ To all the rest of you out there in the ether, it's one of those days. It's one of those lifes. And I've had the same song stuck in my head for weeks and now I can't remember a word. It's something like ""I'm With You"" by some girl. Got it stuck in my head in the bus station in Texas, and now I've lost it. Lost a lot of things. And I can't find the shirt - which oddly enough, is the thing that currently matters most. I'll be seeing you.",male
...,...,...
676621,mood: omg listening to: ... me and sharons hosting the jap students.. its gonna be so fun.. haha. portugal rox!,female
676622,"mood:tired listening to: the air con buzzing sigh. Exams are in like 2 days?! And I'm still online!? This is so shitified. Anyway, please lah. It's just football. Ok. maybe not JUST football but yar, you all roughly get what I mean right? So cool down people. God loves you all and so does Liz who has a massive stomachache now... So seeya guys/gurls.",female
676623,"mood: stressed!! listening to: someday by nickelback hey! sorry just dropped by to tell everyone that part two will be up AFTER THE EXAMS! hehe. oh yeah and pls stop the tagboard war can. the euro doesn't affect us in any way, we don't stand to lose or gain from it do we?",female
676624,"mood: tired listening to: heal the world-michael jackson[yesyes. jacko wacko] where's everyone!?! a good answer would be buried under a big pile of assesment books...heh. Have to admit. I'm turning into a Melody too! ;) Anyhoos Sze, i heard Winnie So's going on the Hong Kong trip as well... Like erm ok... So who's hosting Jap students? Oh and Mich, where's part two of the story?!!! Haha/",female
676625,"mood: - listening to: the windchime tinkling hey ppl. my b'dae is coming soon and all of the RTOL ppl are invited to my b'dae party. its on a saturday, the 28th august. so try to make tt day free if u wanna come. =).. btw, whys this bloggie so ddd",female

In [55]:
def remove_chat_format_rows(df, text_column):
    """
    Chat log formatında yazılmış satırları kaldırır.
    - Birden fazla timestamp varsa (çoklu mesaj)
    - Veya başında "Username (HH:MM AM/PM):" formatı varsa (tekli mesaj)
    """
    # çoklu timestamp kontrolü (önceki sistem)
    multi_time_pattern = r'(\d{1,2}:\d{2}\s?(?:AM|PM))'

    # tekli chat formatı: Username (HH:MM AM/PM):
    single_chat_pattern = r'^[^\n]{1,40}\s\(\d{1,2}:\d{2}\s?(?:AM|PM)\):'

    def is_chat_line(text):
        time_matches = re.findall(multi_time_pattern, text, flags=re.IGNORECASE)
        single_line_match = re.match(single_chat_pattern, text, flags=re.IGNORECASE)
        return len(time_matches) >= 2 or bool(single_line_match)

    df_cleaned = df[~df[text_column].apply(is_chat_line)].copy()
    df_cleaned.reset_index(drop=True, inplace=True)
    return df_cleaned

df = remove_chat_format_rows(df, text_column="text")

df

,text,gender
0,It's getting COLD!!!! what the hell is going on?? *Shakes head in disgrace* but its a funny thing...my house feels like I have...get this...AIR CONDITIONING....geee. Well...I am deciding if I would still want to go see the West Side Story outside on a big screen...it's supposed to start by sundown but it looks like it's gonna rain...so maybe not. I had the wierdest dream....I WAS XENA!! lol and i was eating....cheese!! Cheese apparently made me invincible..it was scary. But who doesnt love cheese....^_^ now that u've read this...go on...I urge you...have some cheese *WINK*,male
1,"Hey I know its a little late, but I just found this image, it cracked me up! By the way it's from urlLink Beer Monkey The image that was perviously here awas messing up the site design so I removed it. If you want to see it urlLink click here .",male
2,"Well, I'm an idiot! But a reasonably happy one, nonetheless. I figured out why the AP people never sent me my scores . . . I filled out the address thing wrong. Can you believe that?! How *much* intelligence does it take to bubble something in properly??? I don't even want to know what I got anymore - if I can't write my own name and address, I certainly can't pass the stupid test. Unfortunately, now that I've decided I really *am* just that stupid, they've gotten my actual address and are going to remail my scores. *buries head in hands* In other news . . . um, I figured out how to delete posts all on my own. It's kind of fun - so if anyone's been seeing posts that suddenly disappear five minutes later, that's just me reveling in my one discovered technological skill. It's about the only thing I *can* do. And Conrad. . . you're definitely my favorite little brother ever. Love you lots - maybe we should make a calendar and start marking down days? ^_~ Later!",male
3,"Well...I thought I would make one post before I went to bed so here it is. POST. Anyway saw some friends and had some fun, besides that today was very uneventful. Think tomorrow will be the same, G'night all hope Satan doesn't wake you",male
4,"Conrad's taught me how to post - I thought I knew, but apparently it takes more effort. Wow, that's ironic. Dollface, dearest love of my life, I'm going to try to call you later, but be prepared to pick up for a phone number you don't know. LadyNeptune - well, first get a shorter name ^_^ - and I'll try to call you, too. How could I not try to get ahold of my favorite lesbian lover? And Conrad - you're definitely the best friend a demented gypsy could ask for. Even if you won't admit you're my little brother. Sedgie - were you wearing the necklace this morning? I didn't notice - and we're so calling you Sedgie from now on. ^_^ To all the rest of you out there in the ether, it's one of those days. It's one of those lifes. And I've had the same song stuck in my head for weeks and now I can't remember a word. It's something like ""I'm With You"" by some girl. Got it stuck in my head in the bus station in Texas, and now I've lost it. Lost a lot of things. And I can't find the shirt - which oddly enough, is the thing that currently matters most. I'll be seeing you.",male
...,...,...
652867,mood: omg listening to: ... me and sharons hosting the jap students.. its gonna be so fun.. haha. portugal rox!,female
652868,"mood:tired listening to: the air con buzzing sigh. Exams are in like 2 days?! And I'm still online!? This is so shitified. Anyway, please lah. It's just football. Ok. maybe not JUST football but yar, you all roughly get what I mean right? So cool down people. God loves you all and so does Liz who has a massive stomachache now... So seeya guys/gurls.",female
652869,"mood: stressed!! listening to: someday by nickelback hey! sorry just dropped by to tell everyone that part two will be up AFTER THE EXAMS! hehe. oh yeah and pls stop the tagboard war can. the euro doesn't affect us in any way, we don't stand to lose or gain from it do we?",female
652870,"mood: tired listening to: heal the world-michael jackson[yesyes. jacko wacko] where's everyone!?! a good answer would be buried under a big pile of assesment books...heh. Have to admit. I'm turning into a Melody too! ;) Anyhoos Sze, i heard Winnie So's going on the Hong Kong trip as well... Like erm ok... So who's hosting Jap students? Oh and Mich, where's part two of the story?!!! Haha/",female
652871,"mood: - listening to: the windchime tinkling hey ppl. my b'dae is coming soon and all of the RTOL ppl are invited to my b'dae party. its on a saturday, the 28th august. so try to make tt day free if u wanna come. =).. btw, whys this bloggie so ddd",female

In [56]:
import re

def is_likely_quoted(text):
    if len(text) < 300:
        return False

    # tırnak içinde uzun metin
    if re.match(r'^\s*["“].+["”]\s*$', text, re.DOTALL):
        return True

    # yaygın quote keyword'leri
    keywords = ['by ', 'source:', 'quoted from', 'excerpt', 'taken from', '--', '~', 'via ', 'posted by']
    if any(kw in text.lower() for kw in keywords):
        return True

    return False

df = df[~df["text"].apply(is_likely_quoted)].copy().reset_index(drop=True)

df

,text,gender
0,"Hey I know its a little late, but I just found this image, it cracked me up! By the way it's from urlLink Beer Monkey The image that was perviously here awas messing up the site design so I removed it. If you want to see it urlLink click here .",male
1,"Well...I thought I would make one post before I went to bed so here it is. POST. Anyway saw some friends and had some fun, besides that today was very uneventful. Think tomorrow will be the same, G'night all hope Satan doesn't wake you",male
2,"All right...New site coming up, same people, but fresher posts and fresher, yet retro look. I call it Barrels Of Monkeys, its still a work in progress. Shari, Gen. Sed., Summer, Lady Neptune and I are all going to blog it. Hope you'll enjoy the fresh look, coming up next week (hopefully). Anyway back to bussiness. Today NYC experienced the worst weather, we had ten-mintute thunderstorms. TEN MINTUES , what good is that? It's like fucking mintute men who can barely last, curse you minute men...Brings back memories of old...of Africa. Man, I am one sad mo-fo monkey, anyway peace out, keep your head out of the OJ.",male
3,"THE THREE MOST ANNOYING EYESORES IN NEW YORK CITY (seriously these things are really annoying) : The New Hummer. Not only is this crap ugly, but it takes up the parking space of a mini van, and then some of the active road. Not only that, but it gets like negative four mile per gallon. Those really annoying scooters. The people who use these machines are lazier than hipoes. I can walk faster than most of them. They have wheels! Yet they want a petrol guzzling machine that will take them 10 miles per day. Why not get a mo-ped, even they are better! These scooters might have been less annoying if they were quieter, but nope, not even that. Last but not least, the new Mc.Ds. It uses more electricity than a entire subway line. Tsk, Tsk, Tsk, and I had to witness them all on friday, poor poor me. 8(",male
4,"Hello all, Greetings my minions, I am the General, General Sedgwick to be exact, and welcome to my first post, i dont suppose I have much to say. Im suffering a major case of seperation anxiety from the Summer Gypsy who has posted previously in this domain. I'm also rather tired, but thats my own fault, so I cant really complain can I. Well, i suppose that'll be all then, ta for now.",male
...,...,...
445604,mood: omg listening to: ... me and sharons hosting the jap students.. its gonna be so fun.. haha. portugal rox!,female
445605,"mood:tired listening to: the air con buzzing sigh. Exams are in like 2 days?! And I'm still online!? This is so shitified. Anyway, please lah. It's just football. Ok. maybe not JUST football but yar, you all roughly get what I mean right? So cool down people. God loves you all and so does Liz who has a massive stomachache now... So seeya guys/gurls.",female
445606,"mood: stressed!! listening to: someday by nickelback hey! sorry just dropped by to tell everyone that part two will be up AFTER THE EXAMS! hehe. oh yeah and pls stop the tagboard war can. the euro doesn't affect us in any way, we don't stand to lose or gain from it do we?",female
445607,"mood: tired listening to: heal the world-michael jackson[yesyes. jacko wacko] where's everyone!?! a good answer would be buried under a big pile of assesment books...heh. Have to admit. I'm turning into a Melody too! ;) Anyhoos Sze, i heard Winnie So's going on the Hong Kong trip as well... Like erm ok... So who's hosting Jap students? Oh and Mich, where's part two of the story?!!! Haha/",female
445608,"mood: - listening to: the windchime tinkling hey ppl. my b'dae is coming soon and all of the RTOL ppl are invited to my b'dae party. its on a saturday, the 28th august. so try to make tt day free if u wanna come. =).. btw, whys this bloggie so ddd",female

In [57]:
import re

def clean_noisy_rows(df, text_column="text", remove_short=True, min_length=15):
    def is_chat_log(text):
        # çoklu timestamp ya da Username (HH:MM AM/PM): şeklinde
        multi_time_pattern = r'(\d{1,2}:\d{2}\s?(?:AM|PM))'
        single_line_pattern = r'^[^\n]{1,40}\s\(\d{1,2}:\d{2}\s?(?:AM|PM)\):'
        return len(re.findall(multi_time_pattern, text, flags=re.IGNORECASE)) >= 2 or \
               re.match(single_line_pattern, text, flags=re.IGNORECASE)

    def is_urllink_line(text):
        return text.lower().count("urllink") >= 2 or text.lower().startswith("urllink")

    def is_quoted_line(text):
        if len(text) < 300:
            return False
        if re.match(r'^\s*["“].+["”]\s*$', text, re.DOTALL):
            return True
        keywords = ['by ', 'source:', 'quoted from', 'excerpt', 'taken from', '--', '~', 'via ', 'posted by']
        return any(kw in text.lower() for kw in keywords)

    def is_too_short(text):
        return len(text.strip()) < min_length

    def is_noisy(text):
        return is_chat_log(text) or is_urllink_line(text) or is_quoted_line(text) or (remove_short and is_too_short(text))

    df_cleaned = df[~df[text_column].apply(is_noisy)].copy()
    df_cleaned.reset_index(drop=True, inplace=True)
    return df_cleaned

df = clean_noisy_rows(df, text_column="text")

df

,text,gender
0,"Well...I thought I would make one post before I went to bed so here it is. POST. Anyway saw some friends and had some fun, besides that today was very uneventful. Think tomorrow will be the same, G'night all hope Satan doesn't wake you",male
1,"All right...New site coming up, same people, but fresher posts and fresher, yet retro look. I call it Barrels Of Monkeys, its still a work in progress. Shari, Gen. Sed., Summer, Lady Neptune and I are all going to blog it. Hope you'll enjoy the fresh look, coming up next week (hopefully). Anyway back to bussiness. Today NYC experienced the worst weather, we had ten-mintute thunderstorms. TEN MINTUES , what good is that? It's like fucking mintute men who can barely last, curse you minute men...Brings back memories of old...of Africa. Man, I am one sad mo-fo monkey, anyway peace out, keep your head out of the OJ.",male
2,"THE THREE MOST ANNOYING EYESORES IN NEW YORK CITY (seriously these things are really annoying) : The New Hummer. Not only is this crap ugly, but it takes up the parking space of a mini van, and then some of the active road. Not only that, but it gets like negative four mile per gallon. Those really annoying scooters. The people who use these machines are lazier than hipoes. I can walk faster than most of them. They have wheels! Yet they want a petrol guzzling machine that will take them 10 miles per day. Why not get a mo-ped, even they are better! These scooters might have been less annoying if they were quieter, but nope, not even that. Last but not least, the new Mc.Ds. It uses more electricity than a entire subway line. Tsk, Tsk, Tsk, and I had to witness them all on friday, poor poor me. 8(",male
3,"Hello all, Greetings my minions, I am the General, General Sedgwick to be exact, and welcome to my first post, i dont suppose I have much to say. Im suffering a major case of seperation anxiety from the Summer Gypsy who has posted previously in this domain. I'm also rather tired, but thats my own fault, so I cant really complain can I. Well, i suppose that'll be all then, ta for now.",male
4,iiiiiits..a small world...aaaaafter alll!!! yea its me....writing cuz mr. CONRAD asked me to lol....so i saw pirates of the carribean..actually pretty good..FUNNY....then i went back home..and it was BORING again lol. la la la....so i played starcraft ms. gyspsy!!! lol crazy i kno. so off i go!! muahz!,male
...,...,...
375356,mood: omg listening to: ... me and sharons hosting the jap students.. its gonna be so fun.. haha. portugal rox!,female
375357,"mood:tired listening to: the air con buzzing sigh. Exams are in like 2 days?! And I'm still online!? This is so shitified. Anyway, please lah. It's just football. Ok. maybe not JUST football but yar, you all roughly get what I mean right? So cool down people. God loves you all and so does Liz who has a massive stomachache now... So seeya guys/gurls.",female
375358,"mood: stressed!! listening to: someday by nickelback hey! sorry just dropped by to tell everyone that part two will be up AFTER THE EXAMS! hehe. oh yeah and pls stop the tagboard war can. the euro doesn't affect us in any way, we don't stand to lose or gain from it do we?",female
375359,"mood: tired listening to: heal the world-michael jackson[yesyes. jacko wacko] where's everyone!?! a good answer would be buried under a big pile of assesment books...heh. Have to admit. I'm turning into a Melody too! ;) Anyhoos Sze, i heard Winnie So's going on the Hong Kong trip as well... Like erm ok... So who's hosting Jap students? Oh and Mich, where's part two of the story?!!! Haha/",female
375360,"mood: - listening to: the windchime tinkling hey ppl. my b'dae is coming soon and all of the RTOL ppl are invited to my b'dae party. its on a saturday, the 28th august. so try to make tt day free if u wanna come. =).. btw, whys this bloggie so ddd",female

In [58]:
df["text"] = df["text"].str.replace(r"\burlLink\b", "", regex=True)
df = df[~df["text"].str.startswith("mood:", na=False)].copy()

def is_useless_line(text):
    if not isinstance(text, str):
        return True
    lowered = text.lower()

    # şarkı/müzik dinleme ya da tv izleme odaklı cümleler
    if lowered.startswith("listening to:") or lowered.startswith("watching:"):
        return True

    # blog layout/template/meta yorumları
    if any(kw in lowered for kw in ["tagboard", "template", "blog layout", "click here", "bgcolor"]):
        return True

    return False

df = df[~df["text"].apply(is_useless_line)].copy()
df.reset_index(drop=True, inplace=True)

In [59]:
import re

def contains_html_or_code(text):
    if not isinstance(text, str):
        return False

    # HTML etiketleri
    html_tag_pattern = r"<[^>]+>"

    # CSS stilleri
    css_style_pattern = r"style\s*=\s*['\"].*?['\"]"

    # JavaScript snippet'leri
    js_snippet_pattern = r"<script.*?>.*?</script>"

    return bool(re.search(html_tag_pattern, text)) or \
           bool(re.search(css_style_pattern, text)) or \
           bool(re.search(js_snippet_pattern, text, flags=re.DOTALL))

# uygula ve temizle
df = df[~df["text"].apply(contains_html_or_code)].copy()
df.reset_index(drop=True, inplace=True)

In [60]:
import re

def is_useless_blog_line(text):
    if not isinstance(text, str):
        return False  # boş veriyle uğraşma
    lowered = text.strip().lower()

    # 1. sadece link veya urllink placeholder
    if re.fullmatch(r"(https?:\/\/\S+|www\.\S+)", lowered) or "urllink" in lowered:
        return True

    # 2. medya başlıkları (dinliyorum, izliyorum, oynuyorum gibi)
    if any(lowered.startswith(prefix) for prefix in ["listening to:", "watching:", "playing:", "currently listening to:", "now playing:"]):
        return True

    # 3. blog yapısal ifadeleri
    blog_meta_keywords = ["tagboard", "template", "layout", "click here", "bgcolor", "music player", "blogskin"]
    if any(kw in lowered for kw in blog_meta_keywords):
        return True

    # 4. sadece tarih, başlık ya da çizgi
    if re.fullmatch(r"\w+,\s\d{1,2}(st|nd|rd|th)?\s\w+", lowered):  # örnek: "Monday, 5th April"
        return True
    if lowered.strip() in ["---", "entry", "update"]:
        return True

    return False

# uygula ve temizle
df = df[~df["text"].apply(is_useless_blog_line)].copy()
df.reset_index(drop=True, inplace=True)

In [61]:
df

,text,gender
0,"Well...I thought I would make one post before I went to bed so here it is. POST. Anyway saw some friends and had some fun, besides that today was very uneventful. Think tomorrow will be the same, G'night all hope Satan doesn't wake you",male
1,"All right...New site coming up, same people, but fresher posts and fresher, yet retro look. I call it Barrels Of Monkeys, its still a work in progress. Shari, Gen. Sed., Summer, Lady Neptune and I are all going to blog it. Hope you'll enjoy the fresh look, coming up next week (hopefully). Anyway back to bussiness. Today NYC experienced the worst weather, we had ten-mintute thunderstorms. TEN MINTUES , what good is that? It's like fucking mintute men who can barely last, curse you minute men...Brings back memories of old...of Africa. Man, I am one sad mo-fo monkey, anyway peace out, keep your head out of the OJ.",male
2,"THE THREE MOST ANNOYING EYESORES IN NEW YORK CITY (seriously these things are really annoying) : The New Hummer. Not only is this crap ugly, but it takes up the parking space of a mini van, and then some of the active road. Not only that, but it gets like negative four mile per gallon. Those really annoying scooters. The people who use these machines are lazier than hipoes. I can walk faster than most of them. They have wheels! Yet they want a petrol guzzling machine that will take them 10 miles per day. Why not get a mo-ped, even they are better! These scooters might have been less annoying if they were quieter, but nope, not even that. Last but not least, the new Mc.Ds. It uses more electricity than a entire subway line. Tsk, Tsk, Tsk, and I had to witness them all on friday, poor poor me. 8(",male
3,"Hello all, Greetings my minions, I am the General, General Sedgwick to be exact, and welcome to my first post, i dont suppose I have much to say. Im suffering a major case of seperation anxiety from the Summer Gypsy who has posted previously in this domain. I'm also rather tired, but thats my own fault, so I cant really complain can I. Well, i suppose that'll be all then, ta for now.",male
4,iiiiiits..a small world...aaaaafter alll!!! yea its me....writing cuz mr. CONRAD asked me to lol....so i saw pirates of the carribean..actually pretty good..FUNNY....then i went back home..and it was BORING again lol. la la la....so i played starcraft ms. gyspsy!!! lol crazy i kno. so off i go!! muahz!,male
...,...,...
370094,"Shad is fun. Let me get that out right away. Despite all the hard work, the long days, and the excessive time management, Shad is fun. Despite the fact that you're always keeping track of a zillion different things, trying to make sure that nothing is forgotten: no speaker left unthanked, no Late Night left unplanned, no committee meeting skipped. Shad is fun. Plain and simple. Sure, it's not fun in the same way that going out to a party with a group of friends is. It's not fun in the same way that Christmas morning is. But it is fun. Make no mistake about that. I think it's because of the people. You spend everyday with the same group of people. Every minute from when announcements start at 8:30 till Late Night finishes at 10:50 is spent with the same group of people. Naturally, you get to be pretty close pretty quick. I have my own little clique of friends that I hang out with, but I like to think that I can talk/chill/hang with anyone here. I'm just that charming, you see. I think now would be a good time to tell you about my ""clique"" (although Shad emphasizes interacting with EVERYONE, we all know that that just isn't feasible and that it's better to make strong ties with a small group of friends than superficial ties with a larger one). Quite simply put, we're the ""cool group."" That's at least the way it seems here. I think that in a more normal setting, we'd just be the kids with the best social skills. But here... well, you know what they say about the one-eyed man in the land of the blind. We're normal kids. We enjoy partying, having a good time with our friends, and just generally being teenagers. We're the ones who think that the penis game is funny. We think that various euphemisms for ""penis"" are funny. We build giant cocks in the sand. We're kids. There's Rosie, Angus, Rory, Stephanie, Ashok, Dan, John, Lisette, Luna, Melissa, and Sheila. Rosie's from H-town (Hamilton, for those of you not in the know), and she's pretty cool. Good taste in music. Angus is from some rural place in Cape Breton, and has the craziest accent you could ever imagine. He's a DJ, and pretty funny. Rory is the guy that I have the most inside jokes with. He does a lot of acting (well, auditions), and hails from rural New Brunswick (somewhere near Moncton). Stephanie is from Charlottetown. Rory and I have a lot of potato jokes about her (put the potato in the oven and what comes out nine months later? Tater tots! Skin the potato... with your TEETH!). Ashok is a pretty cool dude from Long Island, NY. He originally lived in Mississauga, so he understands my O-town blues. Dan's from Hamilton too. Heavy on the football. Good guy. John's a pretty funny dude from the T-dot. Plays a pretty mean set of bagpipes too. Lisette is awesome. She's a blonde bombshell from Cape Breton. Those Nova Scotians have the damn hottest accents ever. Luna's from New Market. Craziest girl I know. Melissa's a very sweet girl from Calgary. Sometimes kinda blonde, but a definite sweetheart. Sheila's pretty awesome too. She's from Dryden, a small town in Northern Ontario. She's diabetic, but has a really positive outlook on life. I love her to bits. Ah, who am I kidding... I love 'em all to bits. There are other people I'm friends with too, but those are the ones that I spend most of my free time with. I'll tell you all about Green House... but not till tomorrow. I've got a super-important meeting to get to now. Lotsa love to the O-tizzle from the O-dot, - Cary",male
370095,"It's already been nine days. I'm amazed. It doesn't really feel like nine days at all - what it really feels like is nine days or nine seconds, all at the same time. My mind's been awhirl all that time, always rushing from one activity to the next. Our time is highly regulated; we'll have anywhere from 4-6 hours a day of lectures, and an equal amount of time spent in activities. We're on from 8:30 in the morning till 11 at night, no exceptions. Shad Valley is all about excellence, afterall. Some of the lectures are incredibly boring and excellent at inducing heavy amounts of sleep. I'll tell you guys all about it later, but right now I have to go to a Diaster Fair. What's a Diaster Fair, you ask? I have no idea. Check in later. Cheers from Carleton, - Cary Back Again I suppose I should talk a little bit about what we actually do here at Shad Valley. Of course I mention the lectures and the activities, but I don't mention what those actually are , what their point is. All these activities and workshops and lectures are supposed to be helping us with one of two things: our teambuilding skills, or the DE Project. Since most of you know what teambuilding skills are, I'll go into what the DE Project is. Every year Shad Valley participants are assigned a theme. It's common to all campuses aross Canada; we all have the same amount of time to work on it, same amount of resources, etc. We have to design a device that deals with this theme. Not only do we have to design the device, but also a working prototype, a business plan, a corporate website, a marketing package, and a promotional package. It's a fair bit of work for three weeks. No one really knows what the ""DE"" in ""the DE Project"" stands for. Some speculate that it stands for ""disaster and emergency,"" this year's theme. Others believe that it stands for ""design and engineering."" But no one knows for sure. We only get about 2 hours of DE Project time a day. Considering the amount of work we have to do, that's not a lot of time. Not a lot at all. So we must be fairly efficient. That's where the teambuilding skills come into play. If you can't work together as a team you're going to fail. Plain and simple. Luckily, my house work together incredibly well. We may not have the coolest people, or the most technically knowledgeable, or the most physically skilled; but, we do have the house that works best together. The most important part of our team dynamic is how we listen. Every meeting the house has, whether it be regarding the DE Project or not, we assign a different chairperson to chair the meeting. The chair's responsibilities are to basically let only one person talk at a time and keep the others quiet. This gives everyone in the group a leadership role at one time or another, and gives those who would not otherwise make themselves heard a voice. It didn't used to be this way, however. Prior to the rotating chair system, we relied on two leaders: myself, and my friend from Nanaimo, Stephen. Being a leader among leaders is quite the feeling, let me tell you. The system worked well enough: there was order and control, and everyone was heard. However, it didn't really reflect the values of Shad, and that wasn't a good thing. Anyhow, it's about 8:21, and I have to get to a lecture for 8:30. More to come later. Cheers from Stormont, - Cary",male
370096,Not a test. Just a quiz.,male
370097,And write what's true.,male
370098,"catdog CATdog [catdog] a lonely little world with a little catdog CATdog [catdog] a lonely little world with a little catdog!!! haha. so farny. my bro singing the song while i'm typing it. well wanda i second that motion; damn sian at home! but parents are like your exams coming already arh better study! wanda you no exams meh? eh you're online i ask you. haha. okay you're not responding. anyway gotta go back to studying now. or not. today's supposed to be geog, amaths and bio which is not too bad. anyone besides liz and me going cca leaders camp? somebody provide us with the details? or else we'll like gatecrash at school at 6AM so we don't miss the bus or something. heh heh. who's supporting england for euro? ME!!!",female

In [62]:
combined_path = "/content/drive/MyDrive/datasets/combined_gender_text_dataset.pkl"

with open(combined_path, "rb") as f:
    df_combined = pickle.load(f)

df_merged = pd.concat([df, df_combined], ignore_index=True)

df_merged = df_merged[df_merged["text"].str.len() >= 15].copy()

min_count = df_merged["gender"].value_counts().min()
df_balanced = df_merged.groupby("gender").sample(n=min_count, random_state=63).reset_index(drop=True)

df_balanced

,text,gender
0,"lol, ehh...it's 1:15 right now...so I don't think I'm gonna come. I might plan on coming to the JournalCon, though. That does sound a bit interesting. hehe. anyways...I'm going to go get beautified cuz my mom's paying. lol, I sound like such a barfy girl. Okay, I'm just going to stop. Have a good day, everyone! I don't like it. I don't like it at all.",female
1,"Good morning, sir. Can you tell me the bus connection to the airport from Fosa Street is at the Nowoursynowska Valley of Służewiecka.",female
2,celts undoubtedly were driven into the west and sought refuge in wales and cornwall,female
3,So tired of school...so tired of seeing you with her...you can both burn,female
4,"When the road gets dark, And you can no longer see, Let my love throw a spark, Have a little faith in me, And when the tears you cry, Are all you can believe, Just give these loving arms a try baby, and Have a little faith, faith in me Have a little faith in me Have a little faith in me, oh and Have a little faith in me Have a little faith, faith in me When your secret heart, Cannot speak so easily, Come here baby, from a whisper start, To have a little faith in me, And when your back's against the wall, Just turn around and you, you will see I will catch your, I will catch your fall just, Have a little faith,faith in me Have a little faith in me Have a little faith in me Have a little faith in me Have a little faith, faith in me I've been loving you for such a long, long time, Expecting nothing in return, Just for you to have a little faith in me, You see time, time is our friend, Caus the rest is the end, All you gotta do is have a little faith. I will hold you up, I will hold you up and, Your love gives me strength enough to, Have a little faith in me, Oh faith, darlin' Have a little faith in me Oh, faith This song has really hit me hard, with everything that's gone on lately! But, i mean, i just wanna have break through and tell people, to have a lil faith me, b/c ima be alright! I mean, i kind of...had my lil ""breakdown"" if that's what you want to call it, these past coupla days, but, i'm fine now, and i realized, that i'll be fine in the long run also! It feels great comin to this realization...b/c i know and god showed me last night...that i'll be alright, and, that sometimes, it's ok to cry, and it's ok to let everything out...because if you don't, you keep it in, and then, your emotions start to get mixed up, and you get confused. So, it's ok, and I know i'm goin to be ok! But, i gotta go now, bye bye, Love, Lauren",female
...,...,...
461327,"Hiya, I am happier than i have been for weeks and weeks, Last night i took out Wayne for his surprise, we went in a limo with both of our gfs to london to see, 'The Lion King' Finished me off financially, but was the best night i have had for so long, months. And was worth it for the look on his face and the hugg i got. So i am happy, check my msn window for a pic of us in the limo. Eventually me and nicki will have a site back up ready and online so the whole picture sharing thing will be easy again. I hope you're all as happy as i am, or happy. Say 'HI' to Vee for me Jackie, Nicki, a plan for your woolworths theives, 'take a shot gun to work!' Speak to you all soon, Dave",male
461328,"I have an extremely bad habit of staying up till the wee hours of the morning watching retarded, pointless tv shows. Last night at 1:30 Elimidate came on. If you aren't familiar with it, it's about these 4 people competing for one person of the opposite sex. So basically it's a bunch of whores giving lap dances to the lucky guy. Then another episode came on, and I felt compelled to watch it. This is what happens at 2 in the morning, you want to go away but you can't because either you are a weirdo who likes elimidate or you just watched a scary movie and can't it out of your head. So I stayed up until around 2:30 and then I went upstairs read my book and finally settled down around 3. DON'T EVER DO THAT. P.S. I'm not the weirdo... I had just watched Identity again. P.P.S. I know the Norma Jean link is weird but I couldn't think of anything to say.",male
461329,"Today was so weird. There was snow in April?! Oh well, no track but we were one of the only schools not closed. All the schools around us were closed. At least we'll get a longer vacation in a couple of weeks. Nothing really happened today except my computer was acting all bitchy. I did homework, read some greek mythology with a labyrinth and a dude flies and his wings melt and he falls into the ocean, watched Men In Tights, played drums, talked online, listened to music, ate ice cream in a waffle bowl and then fell asleep... well I'm doing that now. Good Night. Oh yes, people remind me tomorrow to use my Linkin Park cd to check out the web site maker. Thanks and Good Night.",male
461330,"there are a lot of people who have changed some and i know we all have to change and shift because thats what darwin says we will do, or at least our kids will, or our kids kids. mutation. the boy jill met 2 summer ago isnt me. the boy who proposed to jami rubin on a bet (i also had a huge crush... that lasted a few years) isnt me. the boy who wrestled in junior high isnt me now. We have all changed and it is evident in some of our friends more then others i would say. but its a shame its most evident in my enemies. and its not really my enemies. there are people who i have looked at very close just to see a face below the mask. But we all hide ourselves away to some point. i am not a totally open book, because i want you all to think that i am really cool and smart when you read this. and i know that you dont really think that but wi couldt write this if i thought you didnt think i was smart or clever or something. see this is the kind of things i keep to myself. but its strange because sometiems i look back to nights. when a girl i used to like and i stalked through our streets and talked. well at least i know i talked. Its funny if someone doesnt say anything you assume your having the best conversation ever. and i am guilty of just talking talking talking. i would talk your ear off if you let me. i promise you. i try to remind myself to slow down and be like ""what do you think"" becuase like most people, or at least my vision of most people i usually think im right. For some reason there are certain people that i try to not appear ignorant infront of. AND of course i dont ever want to look dumb but when i talk around Ashley Kaiser i watch my words to not sound like an idiot. and yes i know you are probably saying ""why her?"" and i wish i knew. she just gives off one of those vibes where i feel that i need to respect her even if some of her colums in the school paper made me upset. some people just give off very strong vibes and command my respect, so i have to give it to them. its very strange. There are also certain people who i have to cover my back once i make fun of them, i have to make sure they feel good about themselves after i say something. The one who comes to mind most is boznos. because i make jokes but i really like him a lot and i want him to be sure that i like him because it sucks if someone makes a joke that makes you feel bad. its strange growing up with joe and james. it got me thinking on my feet. and i know that back then it was like ""your gay"" and then i would be like ""no you are... you big gay"" i just remembered this time i wanted to get james in trouble on kwaj. For some reason us brothers were left alone at home with joey at home in charge of us. so that made him able to put us in our rooms. and i wanted to get james in trouble because i had broken the weiner piece on my gijoe because of him. and i was pissed. so we were arguing and i realized if i gave him the bait he woudl take it. so i called him a pussycat and lo and behold he called me a ""pussy"" and that was enough to get him grounded. but we were really mean to each other about 7 years ago. i remember the fights in florida and when we first moved here. and joe never got any shit at all. if only james andi would have teamed up against him. we could have taken that jerk ass down. because he got to make fun of both of us. next time i see joe im punching him. it would mean a lot to me if all of you did the same.",male
461331,"HEy! this is chris quinton klocke. if you know me my real name is christofer david klocke. i always wanted my middle name to be quinton. i dont know y. just sounded cool. my sister's friend's name is quinton. hes cool. any way. ashton kutcher's first name is chris. thats pretty cool. his real name is christofer ashton kutcher. im not sure how to spell his last name. so this is my blog. who the hell decided to call it a blog? i guess they were high. nothing wrong with that. hippies got high. i dont really like hippies. i watched forest gump yesterday. i like that movie. its a good old movie. so is back to the future. old movies rock. except some. like rocky horror picture show. its kinda scary. my sisters friends liked it i guess. jeremy said they got all their fundings from sellin drugs. it has logic to it. im not good at thinking of stuff to type. thats y i named this bunches o' crap. i got an idea. i'll wright a list of bands that kick pop's f**kin ass! seriously. i hate pop. music that is. not the carbonated beverage. i need pop to live. the drink i mean. anyway. heres the list (in alphabetical order)(this is only a few) *Brand New *Coheed and Cambria *Dashboard Confessionals *Dropkick Murphys *Frank Sinatra *Incubus *Kiss *Modest Mouse *MUPPETS (its capitolized cuz they are the coolest) *Queen *Reel Big Fish *Rockapella *Saves the Day *SoCo *Sugarcult *Taking Back Sunday *The Early November *The Starting Line *Weezer This is only a few cuz there are a lot more and im to lazy to write them all. im sick fo writing this ""blog"" (what the hells up with that?). cya",male

In [63]:
import pickle

output_path = "/content/drive/MyDrive/datasets/combinedatasetinformal.pkl"

with open(output_path, "wb") as f:
    pickle.dump(df_balanced, f)